# as we know there're 3 types of triggers in GitHub Actions
# 1. webhook based triggers (push, pull_request, etc.)
# 2. scheduled triggers (cron jobs)
# 3. manual triggers (workflow_dispatch)
on:
  push: # this is webhook based trigger (runs automatically when a push is made)
     # we can specify branches and paths to limit when this trigger runs
    branches:
      - main
      - "release/**" # means any branch that starts with "release/"
    paths:
      - "src/**" # but i want the push trigger to only run when files in src/ are changed
  pull_request: # another webhook based trigger (we can use the same workflow for both triggers)
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: npm test # this will run the test file defined in package.json