on:
  schedule: # this is a scheduled trigger (the second type) (it's used for cron jobs that happens periodically (like backups, report generation, etc. ))
    # runs every day at midnight UTC it takes a list of cron expressions
    # you can specify multiple cron expressions to run at different times
    # every digit represents a time unit (minute, hour, day of month, month, day of week)
    # here we use a cron expression to run the workflow daily at midnight UTC
    - cron: '0 0 * * *' # runs every day at midnight UTC 
    - cron: '0 8 * * *' # runs every day at 8 AM UTC
    - cron: '0 14 * * *' # runs every day at 2 PM UTC

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Running the scheduled task"
